baseURL = "https://dwayne-mcdaniel.com"
languageCode = "en"
title = "Dwayne McDaniel's Personal Blog"
theme = "hugo-theme-nix"


[params]
  Name = "Dwayne McDaniel"
  HeaderUsername = "mcdwayne"
  HeaderHostname = "dwaynemcdaniel"
  About1 = "Dwayne McDaniel is an Open Source enthusiast focused on helping developer and marketers realize the potential of the Jamstack."
  About3 = "This is his personal and technology related blog."
  Welcomemsg = """
						I only hope I can inspire folks the way I have been inspired by so many others. 
-- Dwayne
  """
  ProfilePicture = "/images/IMG_8840.jpg"
  Email = "dwayne@processdigitalconsulting.com"
  GithubID = "mcdwayne"
  InstagramID = "mcdwayne_real"
  LinkedInID = "dwaynemcdaniel"
  TwitterID = "mcdwayne"


[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
