baseURL = "https://dwayne-mcdaniel.com"
languageCode = "en"
title = "Dwayne McDaniel's Personal Blog"
theme = "hugo-theme-nix"


[params]
  Name = "Dwayne McDaniel"
  HeaderUsername = "mcdwayne"
  HeaderHostname = "dwaynemcdaniel"
  About1 = "Dwayne McDaniel is an Open Source enthusiast focused on process improvement for growing teams."
  About2 = "He loves providing training and helping people get the most out of technology. He also can help you with your WordPress, Drupal and other Open Source web projects."
  About3 = "This is his personal and technology related blog."
  Welcomemsg = """
						Thanks for stopping by! I'd love to chat with you about about process and project management optimization, site building and development, and how we can make the world a better place through Open Source!  
-- Dwayne
  """
  ProfilePicture = "/images/IMG_8840.jpg"
  Email = "dwayne@processdigitalconsulting.com"
  GithubID = "mcdwayne"
  InstagramID = "mcdwayne_real"
  LinkedInID = "dwaynemcdaniel"
  TwitterID = "mcdwayne"


[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
